name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup latest deno version
        uses: denoland/setup-deno@v2

      - name: Publish to JSR
        run: deno publish
